[book]
authors = ["Awiteb"]
language = "en"
multilingual = false
src = "docs"
title = "Lprs Documentation"

[output.html]
git-repository-icon = "fa-git"
git-repository-url = "https://git.4rs.nl/awiteb/lprs.git"
