name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  check_pr_title:
    runs-on: debian
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install git-sumi
        run: |
          curl -s -L "https://github.com/welpo/git-sumi/releases/download/v0.0.6/git-sumi-x86_64-unknown-linux-gnu.tar.xz" -o git-sumi.tar.xz
          tar -xf git-sumi.tar.xz
          mv git-sumi-x86_64-unknown-linux-gnu/git-sumi git-sumi
          chmod +x git-sumi
      - name: Run git-sumi
        run: ./git-sumi "${{ github.event.pull_request.title }}"
